pipeline:
  build:
    image: node:alpine
    commands:
      - npm install

  test:
    image: node:alpine
    commands:
      - npm test

  # trigger:
  #   image: plugins/downstream
  #   server: http://drone.astronomer.io
  #   fork: true
  #   secrets: [ downstream_token ]
  #   repositories:
  #     - astronomerio/astronomer
  #   when:
  #     branch: master
