pipeline:
  build:
    image: node
    commands:
      - npm install

  test:
    image: astronomerio/ap-build:0.0.7
    commands:
      - PG_HOST=database PG_PORT=5432 npm run test

services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # trigger:
  #   image: plugins/downstream
  #   server: http://drone.astronomer.io
  #   fork: true
  #   secrets: [ downstream_token ]
  #   repositories:
  #     - astronomerio/astronomer
  #   when:
  #     branch: master
