pipeline:
  build:
    image: node
    commands:
      - npm install

  test:
    image: node
    commands:
      - sleep 30 # Sleep long enough for postgres to start
      - PG_HOST=database PG_PORT=5423 npm run test"

services:
  database:
    image: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # trigger:
  #   image: plugins/downstream
  #   server: http://drone.astronomer.io
  #   fork: true
  #   secrets: [ downstream_token ]
  #   repositories:
  #     - astronomerio/astronomer
  #   when:
  #     branch: master
