---
version: "2.1"

volumes:
  postgres_data:

services:
  houston-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8870:8870"
    links:
      - postgres-houston
      - postgres-airflow
    depends_on:
      - postgres-houston
      - postgres-airflow
    volumes:
      - ./src:/home/houston-api/src
    environment:
      HOUSTON_POSTGRES_URI: "postgres://houston:houston@postgres-houston:5430/houston"
      AIRFLOW_POSTGRES_URI: "postgres://airflow:airflow@postgres-airflow:5431/airflow"
      AIRFLOW_REDIS_URI: "redis://:password@localhost:6379/0"
      PORT: 8870
      COMMANDER_HOST: "docker.for.mac.localhost"
      COMMANDER_PORT: "50051"
      HELM_GLOBAL_CONFIG: "{\"baseDomain\":\"localhost\",\"acme\":true,\"rbacEnabled\":true,\"tlsSecret\":\"\"}"
      BASIC_AUTHS: |
        admin:$$apr1$$9rplDjuq$$MIjG4yYMg2rB/jAejsOmC1
        user:$$apr1$$emlW4ik.$$Y3V0B6nr/qpI68dGP7HrH1
    entrypoint: ["npm", "run", "dev"]
  postgres-houston:
    image: postgres:9.6
    ports:
      - "5430:5430"
    environment:
      - POSTGRES_USER=houston
      - POSTGRES_PASSWORD=houston
      - POSTGRES_DB=houston
    volumes:
      - ./.local/postgres/houston:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: -p 5430
  postgres-airflow:
    image: postgres:9.6
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./.local/postgres/airflow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: -p 5431
