---
version: "2.1"

services:
  houston-api:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    ports:
      - "8870:8870"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./src:/home/houston-api/src
    environment:
      POSTGRES_URI: "postgres://houston:houston@postgres:5432/houston"
      PORT: 8870
      COMMANDER_HOST: "http://docker.for.mac.localhost"
      COMMANDER_PORT: "8880"

    entrypoint: ["npm", "run", "dev"]
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=houston
      - POSTGRES_PASSWORD=houston
      - POSTGRES_DB=houston
    volumes:
      - ./.local/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
