---
version: "2.1"

volumes:
  postgres_data:

services:
  houston-api:
    environment:
      AUTH_STRATEGY: "local,google_oauth"
      GOOGLE_OAUTH_REDIRECT_URL: "https://houston.astronomer.win/healthz"
      GOOGLE_CLIENT_ID: "405410476024-5ij9hem7854f07lo1pvubjuh8ephp5vq.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "vDsVBypsUFsP-gM4CLOCaIbS"
