---
version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5932:5932"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: -p 5932