---
version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=houston
      - POSTGRES_PASSWORD=houston
      - POSTGRES_DB=houston